## 
# 系统配置文件
##


port: 9696  #服务器的端口号，生成课件后开启一个web服务，便于浏览生成好的页面
#https://www.npmjs.com/package/node-static 静态服务器模块




## 课件设置
title: 课件的名称
icon: ../images/icon.ico  # 课件图标

## 模板设置
tpl: ppt # 使用ppt模板 tpl/ppt文件夹中的内容